name: remind
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2025.11.12
  - libcxx=21.1.5
  - libffi=3.4.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libsqlite=3.51.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=20.0.2
  - python=3.6.15
  - python_abi=3.6
  - readline=8.2
  - setuptools=49.6.0
  - sqlite=3.51.0
  - tk=8.6.13
  - wheel=0.34.2
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - pip:
    - appnope==0.1.4
    - attrs==22.2.0
    - backcall==0.2.0
    - bleach==4.1.0
    - bokeh==2.3.3
    - certifi==2017.7.27.1
    - charset-normalizer==2.0.12
    - cobra==0.17.0
    - colorcet==3.0.1
#    - cplex==12.8.0.0
    - cycler==0.11.0
    - cython==3.0.12
    - deap==1.4.3
    - decorator==4.4.2
    - depinfo==1.7.0
    - docloud==1.0.257
    - docplex==2.4.61
    - future==1.0.0
    - idna==3.10
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - iniconfig==1.1.1
    - ipython==7.16.3
    - ipython-genutils==0.2.0
    - jedi==0.17.2
    - jinja2==3.0.3
    - joblib==1.1.1
    - kiwisolver==1.3.1
    - markdown==3.3.7
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - mpmath==1.3.0
    - networkx==2.5.1
    - numexpr==2.8.1
    - numpy==1.19.5
    - optlang==1.6.0
    - packaging==21.3
    - pandas==1.1.5
    - param==1.13.0
    - parso==0.7.1
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - pluggy==1.0.0
    - prompt-toolkit==3.0.36
    - ptyprocess==0.7.0
    - py==1.11.0
    - pyct==0.4.8
    - pygments==2.14.0
    - pyparsing==3.1.4
    - pytest==7.0.1
    - pytfa==0.9.4
    - python-dateutil==2.9.0.post0
    - python-libsbml-experimental==5.18.0
    - pytz==2025.2
    - pyviz-comms==2.2.1
    - pyyaml==6.0.1
    - requests==2.18.4
    - ruamel-yaml==0.18.3
    - ruamel-yaml-clib==0.2.8
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - seaborn==0.11.2
    - six==1.17.0
    - swiglpk==5.0.12
    - sympy==1.3
    - tables==3.6.1
    - threadpoolctl==3.1.0
    - tomli==1.2.3
    - tornado==6.1
    - tqdm==4.64.1
    - traitlets==4.3.3
    - typing-extensions==4.1.1
    - urllib3==1.22
    - wcwidth==0.2.14
    - webencodings==0.5.1
    - zipp==3.6.0
